### PR TITLE
New kinetic_stereo.launch file that looks up the camera serial numbers

### PR DESCRIPTION
**Pull request by ctkinetic**
Resolves https://github.com/kinetic-auto/manager/issues/98

`kinetic_stereo.launch` is a copy of `kinetic_oc_stereo.launch`.  The lines of interest are where we set the following args: `system_install_path`, `platform_config_path`, `camera_serial_primary`, `camera_serial_secondary`.

Quick demo:

In this instance, I have system00001 installed:
```
> roslaunch spinnaker_camera_driver kinetic_stereo.launch
... logging to /home/cthompson/.ros/log/6e323af6-2654-11ee-be02-4fe5841d4b58/roslaunch-ct-thinkpad-69790.log
Checking log directory for disk usage. This may take a while.
...
 * /stereo/primary/spinnaker_camera_nodelet/serial: 22072264
...
 * /stereo/secondary/spinnaker_camera_nodelet/serial: 22241785
```

Now install system 2:
```
> pushd ~/development/systems-a/ && sudo ./install.py && popd 
[sudo] password for cthompson: 
Default install location is /etc/opt/kinetic/config.  Is this where you want to install? (y/n) y
Installing at /etc/opt/kinetic/config
Configuration exists at /etc/opt/kinetic/config.  Do you want to delete and replace it? (y/n) y
Deleting existing install at /etc/opt/kinetic/config...
Install at /etc/opt/kinetic/config deleted.
Enter system number (1-99999): 2
Using system number 2
...
Installation status: success
```

Run the same roslaunch command again:
```
> roslaunch spinnaker_camera_driver kinetic_stereo.launch
... logging to /home/cthompson/.ros/log/14fa15b6-2655-11ee-be02-4fe5841d4b58/roslaunch-ct-thinkpad-72698.log
...
 * /stereo/primary/spinnaker_camera_nodelet/serial: 22241794
...
 * /stereo/secondary/spinnaker_camera_nodelet/serial: 22073953

```

And just to prove we can still override the serial number arg:
```
> roslaunch spinnaker_camera_driver kinetic_stereo.launch camera_serial_secondary:=99999
... logging to /home/cthompson/.ros/log/83f7123e-2655-11ee-be02-4fe5841d4b58/roslaunch-ct-thinkpad-76081.log
...
 * /stereo/primary/spinnaker_camera_nodelet/serial: 22241794
...
 * /stereo/secondary/spinnaker_camera_nodelet/serial: 99999
```

To be clear, these instances don't actually do anything on my laptop because I don't have those cameras.  I will validate with a camera I have before merging.

### CODE REVIEW

**Review by KNOccamrazor — APPROVED** [review]
Nice Parsing! 
As we are adding the 2nd sensor tower, the platform config may change to:
```
tower1:
     camera_primary:
           serial: xxxx
     camera_secondary:
           serial: xxxx
tower2:
        .... 
```

Should we consider 2nd tower in this pr?

**Comment by ctkinetic** [comment]
> Should we consider 2nd tower in this pr?

Hmm, seems like we should do that when we add logic for more cameras into this driver? @belt-sander do we need to tweak this repo to handle the 2nd tower?

**Comment by ctkinetic** [comment]
Hooked up an old USB BlackFly and GigE Flea3.  They are both found via their serial numbers (had to turn off external triggering for the secondary cam):
```
> roslaunch spinnaker_camera_driver kinetic_stereo.launch
... logging to /home/cthompson/.ros/log/fc60e13a-2661-11ee-be02-4fe5841d4b58/roslaunch-ct-thinkpad-89386.log
...
 * /stereo/primary/spinnaker_camera_nodelet/image_format_roi_width: 1920
...
 * /stereo/secondary/spinnaker_camera_nodelet/serial: 11304169
...
```
Screenshot from 2023-07-19 14-42-51

**Comment by ayushs12** [comment]
LGTM :+1: 

As for,
> >
> do we need to tweak this repo to handle the 2nd tower?

I think @belt-sander has [this branch](https://github.com/kinetic-auto/flir_camera_driver/tree/feature/add-second-tower) that takes care of the second tower but might need some changes based on this PR.

**Review by ayushs12 — APPROVED** [review]

**Comment by ctkinetic** [comment]
> ```
> tower1:
>      camera_primary:
>            serial: xxxx
>      camera_secondary:
>            serial: xxxx
> tower2:
>         .... 
> ```
> 
> Should we consider 2nd tower in this pr?

I tested some yaml changes and the launch file as written works regardless of whether the `camera_primary` and `camera_secondary` are nested under a `tower` node.

When we are ready, we can use very similar python `eval` commands to access the yaml in the second tower (note that the parsing uses index 2 of the : `split('camera_xxx:')`, instead of index 1 for the current code in this branch):
```
  <arg name="camera_serial_primary_t2"
       default="$(eval open(platform_config_path).read().split('camera_primary:')[2].split('serial:')[1].split()[0].strip())"
  /> <!-- MASTER CAMERA -->
  <arg name="camera_serial_secondary_t2"
       default="$(eval open(platform_config_path).read().split('camera_secondary:')[2].split('serial:')[1].split()[0].strip())"
  />
```
I also tested this and it works.

**Comment by belt-sander** [comment]
Sorry I didn't see these comments until now. 

Yes, we will need to make a new PR to apply these changes to `feature/add-second-tower` as this has provisions in the `kinetic_oc_stereo.launch` for all four cameras as opposed to two. @ctkinetic @ayushs12

**Pull request merged**
